language: objective-c

osx_image: xcode7.3

before_install:
        - cd Spec
        - pod install

script: xcodebuild test -workspace ABMultiton.xcworkspace -scheme ABMultiton -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest'
